---
- name: Create a file and add text
  hosts: all

  tasks:
    #- name: Create a directory
    # file:
    #    path: /tmp/george
    #    owner: root
    #    group: root
    #    mode: 0755
    #    state: directory 

  - name: Create a new file
    file:
        path: /tmp/george
        state: touch
  
  - name: Add text to the file
    blockinfile:
        path: /tmp/george
        block: George is one of the main character of Seinfeld show and he is Jerry's best friend
