---
- name: Download Package from a URL
  hosts: all

  tasks: 
   - name: Create a directory /opt/tomcat
     file:
       path: /opt/tomcat
       state: directory
       mode: 0755
       owner: root
       group: root

   - name: Download Tomcat using get_url
     get_url:
       url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.100/bin/apache-tomcat-8.5.100.tar.gz  
       dest: /opt/tomcat
       mode: 0755 
       group: root
       owner: root
