---
- name: Install TMUX and Create directory
  hosts: all

  tasks:
  - name: Create Directory
    file:
      path: /opt/zip
      state: directory
      mode: 0755
      owner: root
      group: root

  - name: Install Tmux package
    get_url:
      url: https://cran.r-project.org/src/base/R-3/R-3.5.0.tar.gz
      dest: /opt/zip
      mode: 0755
      owner: root
      group: root
